default_install_hook_types:
  - pre-commit

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.8.1"
    hooks:
      - id: ruff
        args: [ --fix, --unsafe-fixes ]
        exclude: ^(alembic/|.*\.md$|.*_pb2\.py$|.*_pb2_grpc\.py$)

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^(alembic/|.*\.md$|.*_pb2\.py$|.*_pb2_grpc\.py$)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
        exclude: ^(alembic/|.*\.md$|grpc_server/|.*\.pb2\.py$|.*\.pb2_grpc\.py$)
      - id: end-of-file-fixer
        exclude: ^(alembic/|.*\.md$|.*\.pb2\.py$|.*\.pb2_grpc\.py$)
